class QuotesController < DottedRulers::Controller
  def index
  quotes = FileModel.all
  render :index, :quotes => quotes
  end

  def new_quote
    attrs = {
      "submitter" => "web user",
      "quote" => "Here is a new quote generated by the new_quote method in the quotes controler",
      "attribution" => "Auto generated"
    }
    m = FileModel.create attrs
    render :quote, obj: m
  end

  def show
    quote = FileModel.find(params["id"])
    ua = request.user_agent
    render :quote, obj: quote, ua: ua
  end

  def a_quote
    render :a_quote, verb: :shooed
  end

  def exception
    raise "Holy flocking snitz this is bad!"
  end
  def quote_1
    quote_1 = FileModel.find(1)
    render :quote, :obj => quote_1
  end


end